### PR TITLE
feat: add depot as docker buildx container driver

### PR DESCRIPTION
**Pull request by goller**
```sh
depot configure-docker
```

This adds a buildx driver for the current project in the current working directory and sets that driver as default.

To do this there is a reverse proxy that handles the buildkitd API and forwards it on to depot.
The wrinkle is that the reverse proxy lazily boots a depot builder.  This is because docker desktop continually runs commands to listen for build history and disk usage.  Doing so would keep the depot ephemeral builds runnings indefinitely.

- [x] create `depot driver create` command to create project drivers.
- [x] loop `tlsConn` until connected.
- [x] add support for multi-platform
- [x] stderr logging?
- [x] smart proxy of the buildkitd API to enable steps to be reported.
- [x] decide if we should create a TOML rather than pass env vars; env vars are visible in docker inspect.
- [x] figure out how to update image

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
> add support for multi-platform

I think if you could tell the container which platform it was serving, you'd have multi-platform support with:

```
docker buildx create --name my-depot-project --driver docker-container --driver-opt="image=depot/cli:latest,env.DEPOT_PROJECT_ID=xxx,env.DEPOT_TOKEN=hunter2,env.DEPOT_PLATFORM=amd64" --platform linux/amd64 --buildkitd-flags /usr/bin/buildkitd
docker buildx create --append --name my-depot-project --driver docker-container --driver-opt="image=depot/cli:latest,env.DEPOT_PROJECT_ID=xxx,env.DEPOT_TOKEN=hunter2,env.DEPOT_PLATFORM=arm64" --platform linux/arm64 --buildkitd-flags /usr/bin/buildkitd
```

**Comment by jacobwgillespie** [comment]
> decide if we should create a TOML rather than pass env vars; env vars are visible in docker inspect.

One note on this, when buildx goes to use a `docker-container` driver, it first checks to see if the container exists by name (`buildx_buildkit_[NAME][NUMBER]` so like `buildx_buildkit_my-depot-project0`) and only if it doesn't exist does it launch one.

What that means is that we could (1) create the buildx driver with `buildx create` then (2) create containers with the correct name, using any config we want.

The most straightforward way to share config would be to bind-mount the config dir on the host - that wouldn't work for cases where the Docker daemon was on a separate host (e.g. CircleCI, minikube). But we could create a depot config Docker volume, do the equivalent of `docker cp` to get the config file in there, and mount that in the containers.

That said, realistically I'm not sure that there's much security difference between the token as env vars vs a file if you have access to the Docker socket.

**Review by jacobwgillespie — COMMENTED** [review]
🎉 

On updates, what do you think about a helper function that updates any of our buildx drivers to the latest image reference and looks in Docker for containers matching our name pattern (`depot_XXXXXX_amd64`, etc) and checks to see if their version tag matches the current `build.Version`, and if not it deletes them? Then the next time they're used, they'd pull the latest version I think. We could call that helper from a few places, so that basically as you use the `depot` CLI regularly, it would keep the drivers up-to-date.

For the `buildx use` command, what do you think about `configure-buildx`? Kyle came up with `depot configure-docker` and it might be nice to mirror that.

**Comment by goller** [comment]
Closed in favor of #155

**Comment by jacobwgillespie** [comment]
Re-opening so we can release a proper buildx driver.

**Review by jacobwgillespie — APPROVED** [review]
🎉

**Pull request merged**
